<a href="https://colab.research.google.com/github/Vignesh424/WWE_Super_Card/blob/main/WWE_Supercard_RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [239]:
#import libraries
import numpy as np
import pandas as pd

In [240]:
#read_excel
dataset=pd.read_excel('/content/WWE Super Card.xlsx')

In [241]:
#first 5 columns
dataset.head()

Superstar  Gender     POW     TGH     SPD     CHA    Total Group
0        Adam Cole    Male  269.96  270.46  268.40  272.10  1080.92    WM
1             Akam    Male  269.85  268.93  265.62  265.29  1069.69    WM
2   Aleister Black    Male  269.03  271.20  269.62  267.33  1077.18    WM
3      Alexa Bliss  Female  268.08  265.62  269.55  267.10  1070.35    WM
4  Alexander Wolfe    Male  268.17  266.86  262.53  264.63  1062.19    WM

In [242]:
#shape of data
dataset.shape

(220, 8)

In [243]:
#data description
dataset.describe().round()

POW    TGH    SPD    CHA   Total
count  220.0  220.0  220.0  220.0   220.0
mean   271.0  270.0  270.0  270.0  1081.0
std     64.0   64.0   65.0   64.0   257.0
min    182.0  179.0  180.0  178.0   727.0
25%    193.0  191.0  190.0  191.0   759.0
50%    270.0  270.0  269.0  269.0  1077.0
75%    344.0  344.0  343.0  344.0  1378.0
max    353.0  354.0  351.0  354.0  1400.0

In [244]:
# Preparing the data 
X=dataset.iloc[:,2:7].values
Y=dataset.iloc[:,7].values

In [245]:
X

array([[ 269.96,  270.46,  268.4 ,  272.1 , 1080.92],
       [ 269.85,  268.93,  265.62,  265.29, 1069.69],
       [ 269.03,  271.2 ,  269.62,  267.33, 1077.18],
       ...,
       [ 192.68,  185.47,  189.59,  188.56,  756.3 ],
       [ 196.35,  197.89,  187.81,  188.94,  770.99],
       [ 192.4 ,  189.85,  186.27,  187.79,  756.31]])

In [246]:
Y

array(['WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental

**Training the Data**

In [247]:
from sklearn.model_selection import train_test_split
X_test, X_train, Y_test, Y_train = train_test_split(X, Y, test_size=0.3)

In [248]:
X_train.shape

(66, 5)

In [249]:

X_test.shape

(154, 5)

In [250]:
Y_train.shape

(66,)

In [251]:
Y_test.shape

(154,)

**Use the Model Random Forest**

In [252]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=300)
classifier.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

**Making Predictions**

In [253]:
Y_pred=classifier.predict(X_test)

**Testing the Algorithm**

In [254]:
#classification_report, accuracy_score, confusion_matrix
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
confusion_matrix=confusion_matrix(Y_test,Y_pred)
classification_report=classification_report(Y_test,Y_pred)
accuracy_score=accuracy_score(Y_test,y_pred)

In [255]:
print('Confusion Matrix')
print(confusion_matrix)

Confusion Matrix
[[52  0  0]
 [ 0 44  0]
 [ 0  0 58]]


In [256]:
print('Accuracy')
print(accuracy)

Accuracy
1.0


In [257]:
print('Classification Report')
print(classification_report)

Classification Report
              precision    recall  f1-score   support

   Elemental       1.00      1.00      1.00        52
Royal Rumble       1.00      1.00      1.00        44
          WM       1.00      1.00      1.00        58

    accuracy                           1.00       154
   macro avg       1.00      1.00      1.00       154
weighted avg       1.00      1.00      1.00       154

