<a href="https://colab.research.google.com/github/Vignesh424/WWE_Super_Card/blob/main/WWE_Supercard_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [348]:
import numpy as np
import pandas as pd

In [349]:
data=pd.read_excel('/content/WWE Super Card.xlsx')

In [350]:
data.head()

Superstar  Gender     POW     TGH     SPD     CHA    Total Group
0        Adam Cole    Male  269.96  270.46  268.40  272.10  1080.92    WM
1             Akam    Male  269.85  268.93  265.62  265.29  1069.69    WM
2   Aleister Black    Male  269.03  271.20  269.62  267.33  1077.18    WM
3      Alexa Bliss  Female  268.08  265.62  269.55  267.10  1070.35    WM
4  Alexander Wolfe    Male  268.17  266.86  262.53  264.63  1062.19    WM

In [351]:
data.describe().round()

POW    TGH    SPD    CHA   Total
count  220.0  220.0  220.0  220.0   220.0
mean   271.0  270.0  270.0  270.0  1081.0
std     64.0   64.0   65.0   64.0   257.0
min    182.0  179.0  180.0  178.0   727.0
25%    193.0  191.0  190.0  191.0   759.0
50%    270.0  270.0  269.0  269.0  1077.0
75%    344.0  344.0  343.0  344.0  1378.0
max    353.0  354.0  351.0  354.0  1400.0

In [352]:
data.shape

(220, 8)

In [353]:
X=data.iloc[:,2:7].values
Y=data.iloc[:,7].values

In [354]:
X

array([[ 269.96,  270.46,  268.4 ,  272.1 , 1080.92],
       [ 269.85,  268.93,  265.62,  265.29, 1069.69],
       [ 269.03,  271.2 ,  269.62,  267.33, 1077.18],
       ...,
       [ 192.68,  185.47,  189.59,  188.56,  756.3 ],
       [ 196.35,  197.89,  187.81,  188.94,  770.99],
       [ 192.4 ,  189.85,  186.27,  187.79,  756.31]])

In [355]:
Y

array(['WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental

In [356]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train,Y_test=train_test_split(X,Y,random_state=0,test_size=0.3)

In [357]:
from sklearn.svm import SVC
classifier=SVC()
classifier.fit(X_train,Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [358]:
Y_pred=classifier.predict(X_test)

In [359]:
from sklearn.metrics import *
cm = confusion_matrix(Y_test,Y_pred)
asc = accuracy_score(Y_test,Y_pred)
clr = classification_report(Y_test,Y_pred)

In [360]:
print("Cnfusion_Matrix")
print(cm)

Cnfusion_Matrix
[[21  0  0]
 [ 0 23  0]
 [ 0  0 22]]


In [361]:
print("Accuracy Score")
print(asc)

Accuracy Score
1.0


In [362]:
print("Classification Report")
print(clr)

Classification Report
              precision    recall  f1-score   support

   Elemental       1.00      1.00      1.00        21
Royal Rumble       1.00      1.00      1.00        23
          WM       1.00      1.00      1.00        22

    accuracy                           1.00        66
   macro avg       1.00      1.00      1.00        66
weighted avg       1.00      1.00      1.00        66

