<a href="https://colab.research.google.com/github/Vignesh424/WWE_Super_Card/blob/main/WWE_SuperCard_Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
#import libraries
import numpy as np
import pandas as pd

In [24]:
#read excel file
data=pd.read_excel('/content/WWE Super Card.xlsx')

In [25]:
#Show 5 columns
data.head()

Superstar  Gender     POW     TGH     SPD     CHA    Total Group
0        Adam Cole    Male  269.96  270.46  268.40  272.10  1080.92    WM
1             Akam    Male  269.85  268.93  265.62  265.29  1069.69    WM
2   Aleister Black    Male  269.03  271.20  269.62  267.33  1077.18    WM
3      Alexa Bliss  Female  268.08  265.62  269.55  267.10  1070.35    WM
4  Alexander Wolfe    Male  268.17  266.86  262.53  264.63  1062.19    WM

In [26]:
#Description of Data
data.describe().round()

POW    TGH    SPD    CHA   Total
count  220.0  220.0  220.0  220.0   220.0
mean   271.0  270.0  270.0  270.0  1081.0
std     64.0   64.0   65.0   64.0   257.0
min    182.0  179.0  180.0  178.0   727.0
25%    193.0  191.0  190.0  191.0   759.0
50%    270.0  270.0  269.0  269.0  1077.0
75%    344.0  344.0  343.0  344.0  1378.0
max    353.0  354.0  351.0  354.0  1400.0

In [27]:
#Shape of Data
data.shape

(220, 8)

**Data Preparation**

In [28]:
X=data.iloc[:,2:7].values
Y=data.iloc[:,7].values

In [29]:
X

array([[ 269.96,  270.46,  268.4 ,  272.1 , 1080.92],
       [ 269.85,  268.93,  265.62,  265.29, 1069.69],
       [ 269.03,  271.2 ,  269.62,  267.33, 1077.18],
       ...,
       [ 192.68,  185.47,  189.59,  188.56,  756.3 ],
       [ 196.35,  197.89,  187.81,  188.94,  770.99],
       [ 192.4 ,  189.85,  186.27,  187.79,  756.31]])

In [30]:
Y

array(['WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM',
       'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'WM', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental', 'Elemental',
       'Elemental', 'Elemental', 'Elemental', 'Elemental

**Training the Data**

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test = train_test_split(X,Y,test_size=0.3)

**Choosing the DT Model**

In [32]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

**Prediction Making**

In [33]:
Y_pred=classifier.predict(X_test)

**Testing and Evaluating**

In [34]:
from sklearn.metrics import*
confusion_matrix=confusion_matrix(Y_test, Y_pred)
classification_report=classification_report(Y_test, Y_pred)
accuracy_score=accuracy_score(Y_test, Y_pred)

In [35]:
print("Confusion Matrix")
print(confusion_matrix)

Confusion Matrix
[[25  0  0]
 [ 0 18  0]
 [ 0  0 23]]


In [36]:
print("Classification Report")
print(classification_report)

Classification Report
              precision    recall  f1-score   support

   Elemental       1.00      1.00      1.00        25
Royal Rumble       1.00      1.00      1.00        18
          WM       1.00      1.00      1.00        23

    accuracy                           1.00        66
   macro avg       1.00      1.00      1.00        66
weighted avg       1.00      1.00      1.00        66



In [37]:
print("Accuracy_score")
print(accuracy_score)

Accuracy_score
1.0
